### ISSUE TITLE
[BUG] Error when creating shortcut: CoInitialize has not been called

### ISSUE THREAD

**Issue by n0samu** [oblivioncth/CLIFp#21]
**Describe the bug**
When creating a shortcut via a command like this:
`clifp link --id=6a724774-959a-3628-d867-2b754442a728 --path="C:\Users\nosamu\Desktop"`
An error appears:
"Failed to create shortcut. CoInitialize has not been called."

**To Reproduce**
Run a command like this:
`clifp link --id=6a724774-959a-3628-d867-2b754442a728 --path="C:\Users\nosamu\Desktop"`

**Expected behavior**
Shortcut should be created on the desktop.

**Screenshots**
![image](https://user-images.githubusercontent.com/71368227/197367568-2baeb12f-f17b-422e-845c-a35c14938143.png)

**Version (please complete the following information):**
 - CLIFp version: 0.9.1
- Flashpoint version: 11

**Additional context**
Reported to me here: https://github.com/n0samu/FlashpointShortcutMaker/issues/4

**Comment by oblivioncth** [comment]
@n0samu Hey!

Thanks for bringing this to my attention.

The fix I pushed for this just made it way down the pipeline into a release.
