### ISSUE TITLE
[Feature] Regular Linux build support

### ISSUE THREAD

**Issue by parkerlreed** [oblivioncth/CLIFp#28]
**Is your feature request related to a problem? Please describe.**

Linux build currently assumes the docker solution. 

**Describe the solution you'd like**

Support for the classical launching PHP router and QEMU Gamezip server based on services.json 

**Describe alternatives you've considered**

Currently have a script that is loading everything and hard-coded to a specific game.

```
#!/bin/bash
unset LD_PRELOAD
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
export PATH="$SCRIPT_DIR/FPSoftware/FPWine-8.0:$PATH"
if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
    echo lol
else
    export PATH="$HOME/.local/bin:$HOME/.local/podman/bin:$PATH"
fi
cd $SCRIPT_DIR/Legacy
php -S 127.0.0.1:22600 router.php &
cd $SCRIPT_DIR/Server
qemu-system-i386 -machine pc-i440fx-5.2 -m 128 -net nic,model=virtio-net-pci -net user,hostfwd=tcp:127.0.0.1:22500-:80 -qmp tcp:127.0.0.1:22501,server,nowait -qmp tcp:127.0.0.1:22502,server,nowait -drive file=alpine.qcow2,if=virtio -serial stdio -display none -loadvm quick &
wine start /wait /unix /home/deck/Games/Flashpoint/FPSoftware/Shockwave/PJ101/SPR.exe http://www.candystand.com/games/slipstream/slipstream_1080.dcr --setTheRunMode Plugin --forceTheExitLock 0 --disableGoToNetPage --noDirectX7 --newScriptText "on alertHook me, err, msg --newScriptText return(1)" --do "set the alertHook to script(newScriptMember)" --do "set the resizable of the stage to 0" --do "set the visible of the titlebarOptions of the stage to 0" --do "set the border of the appearanceOptions of the stage to #none" --do "set the rect of the stage to the desktopRectList[1]" --do "set the drawRect of the stage to the desktopRectList[1]" --do "set the fixStageSize to 1"
killall php
killall qemu-system-i386
```

**Additional context**

Script works well enough but CLIFp functionality would be much preferred.

**Comment by parkerlreed** [comment]
I believe so. The thing with the Linux version is you can take the Windows Flashpoint Infinity and remove its Launcher and place in a regular Linux build of the launcher, which is what I've done here. 

I've avoided the actual Linux version because you know docker and Steam Deck don't exactly mix well.

This way you have a Linux launcher that loads a native Linux qemu and php but uses wine for the games as normal.

Essentially you have the Windows services.json with the only custom modification being to replace the qemu-system-i386.exe reference and removing the exe. 

I agree supporting the non standard Linux way is a stretch but for the systems like the Deck where docker isnt really feasible, I think it would be a good addition.

**Comment by parkerlreed** [comment]
I tried adapting Linux Flashpoint's docker approach to podman which can run "rootless" and in the users home directory. podman IS a drop in docker compatible program but it chokes on the virtual network setup.

My current method of obtaining qemu and php because of the Steam Deck immutable fs is to use distrobox and podman to make those binaries available completely without modifying/read write rootfs.

https://gist.github.com/parkerlreed/4bd1f5fa38f7ffa72f9ceacb7d7f636d

**Comment by oblivioncth** [comment]
Huh, I'm surprised I haven't heard of podman yet, though I suppose it does seem to still be up-and-coming. Shame the docker image isn't completely compatible with it though, I guess it would need some tweaks upstream. I wanted to glance at that out of curiosity but I it looks like the keep the docker image configuration on a private GitLab instance.

Anyway, what you're doing makes sense given the limitations you're faced with. I'm honestly surprised that it works as well as it does with so _relatively_ few modifications, though I imagine some of the more obscure platforms may be unknowingly broken if you haven't tried them all.

Regardless, try out this artifact whenever you feel like it: https://github.com/oblivioncth/CLIFp/suites/10805455887/artifacts/543528439

It has the change such that it won't try to wait on docker if the docker image isn't being used as the server, and instead follows normal procedures otherwise. In theory, given that you've configured Flashpoint itself to work properly (as it appears you have), I imagine it should work. There's a lot of moving parts here so I wouldn't get your hopes up too much, but I'm fine trying to tweak things a bit more as long as the changes aren't massive if necessary and it's relatively clear what needs to be done.

Assuming that's all that was needed to at least have it functioning for this use case in a basic capacity, I'll merge the feature branch and push a new release with the change.

**Comment by parkerlreed** [comment]
> though I imagine some of the more obscure platforms may be unknowingly broken if you haven't tried them all.

YES lol. Flash, Shockwave, HTML5 are good bets for working. Java applets work with your own sh. Everything else is a tossup. It's the great wild west!

**Comment by parkerlreed** [comment]
Is there a way to get verbose log from clifp? 

I think flash only worked because it was locally cached by the Projector. New games are having trouble loading just like Shockwave.

If I had to guess the game is being started before php and qemu (mainly) have a chance to get running. Seesm too quick to launch a game when qemu may take 4 seconds to load and the game is up within 2

**Comment by oblivioncth** [comment]
Could be something like that going on. That makes me worry that anyone with a toaster that's tried out CLIFp on desktop has never gotten it working if the Steam deck is too slow and experiences a race condition with QEMU and the game, yikes. Might have to see if like with docker there's a way to query QEMU to see if the VM has completely started and then wait on that.

CLIFp.log, which gets generated in your working directory is all there is, though it's fairly detailed.

**Comment by parkerlreed** [comment]
Funny part is nothing looks out of the ordinary with the launch command

```
 - <11:42:40> [TExec] Started Blocking process 'Slipstream': wine {"start", "/wait", "/unix", "/home/deck/Games/Flashpoint/FPSoftware/Shockwave/PJ101/SPR.exe", ""http://www.candystand.com/games/slipstream/slipstream_1080.dcr" --setTheRunMode "Plugin" --forceTheExitLock 0 --disableGoToNetPage --noDirectX7 --newScriptText "on alertHook me, err, msg" --newScriptText "return(1)" --do "set the alertHook to script(newScriptMember)""}```

As compared to Launcher

```
                                    command:         "wine start /wait /unix "/home/deck/Games/Flashpoint/FPSoftware/Shockwave/PJ101/SPR.exe" "http://www.candystand.com/games/slipstream/slipstream_1080.dcr" --setTheRunMode "Plugin" --forceTheExitLock 0 --disableGoToNetPage --noDirectX7 --newScriptText "on alertHook me, err, msg" --newScriptText "return(1)" --do "set the alertHook to script(newScriptMember)"" ]
```

**Comment by parkerlreed** [comment]
Aha I was able to recreate it outside of clifp

In the output above it's putting extra quotes around the URL and arguments. That's what causes wine to throw that error.

**Comment by parkerlreed** [comment]
It looks like CLIFP is passing all of the arguments as if they are the first argument. If you notice they're not broken up by the same array of double quotes and comma

**Comment by parkerlreed** [comment]
Success :)

![image](https://user-images.githubusercontent.com/841440/217336286-92530430-58fd-41a2-a467-d7af34fc705e.png)

New Flash and New Shockwave working well (As well as existing)

Java works after a Launcher mapping of FPSoftware\startJava.bat to FPSoftware\startJava.sh

I believe CLIFp is now on par with the Linux Flashpoint minus docker! Extra platforms is the same configuration between the two now.

**Comment by parkerlreed** [comment]
Of course I try celebrating too soon. Gamezip mounting seems to have issues.

https://gist.github.com/parkerlreed/6a553cf3dd39d3bad42cfbfb66798756

```
 - <14:25:53> [TMount] QMPI connected to QEMU Version: {"package":"","qemu":{"major":7,"micro":0,"minor":1}} | Capabilities: ["oob"]
 - <14:25:53> [TMount] Creating data pack mount point on QEMU instance...
 - <14:25:53> [TMount] QMPI command blockdev-add {"driver":"raw","file":{"driver":"file","filename":"/home/deck/Games/Flashpoint/Data/Games/887fa483-b9f9-489d-ac5f-7c88335c7946-1664775243535.zip"},"node-name":"ddkacmdpdtybmaie","read-only":true} returned - "{}"
 - <14:25:53> [TMount] QMPI command device_add {"drive":"ddkacmdpdtybmaie","driver":"virtio-blk-pci","id":"ddkacmdpdtybmaie","serial":"Lju4Q\\bSdeXC$@21L,2p"} returned - "{}"
 - <14:25:53> [TMount] Mounting data pack via PHP server...
 - <14:26:05> [TMount] CRITICAL) An error occurred while mounting a data pack. Error transferring http://127.0.0.1:22500/mount.php?file=887fa483-b9f9-489d-ac5f-7c88335c7946-1664775243535.zip - server replied: Bad Request
 - <14:26:05> [driver] Premature end of task 5
 - <14:26:05> [driver] End of task 5
```

**Comment by parkerlreed** [comment]
The only difference I see is CLIFp is passing in the zip name to PHP mount.php while Launcher is passing in the serial

**Comment by parkerlreed** [comment]
Holy crap one I was able to fix myself :D

mounter.cpp I copied the win32 serial usage down to Linux and it works great

```
    QUrlQuery query;
    QString queryKey = "file";
#if defined _WIN32
    QString queryValue = QUrl::toPercentEncoding(mCurrentMountInfo.driveSerial);
#elif defined __linux__
    // FP Launcher uses "basename" but Node.js basename is actually filename
    QString queryValue = QUrl::toPercentEncoding(mCurrentMountInfo.driveSerial);
#endif
    query.addQueryItem(queryKey, queryValue);
    mountUrl.setQuery(query);
```
