### ISSUE TITLE
[BUG] Linux version of Clifp 0.95 and 0.96 not working on Steam Deck

### ISSUE THREAD

**Issue by TheDoomCider** [oblivioncth/CLIFp#67]
**Describe the bug**
I can install the windows version of Flash Point 12 on the Steam Deck and open it with the official launcher. However, when I try to launch it using the windows static version of clifp, either nothing happens or I get an error message that the program didn't terminate correctly. I tried both Proton 7 and 8.

**To Reproduce**
1. Download Flashpoint 12 (archive version or installer (used windows for the installer))
2. Updated it in Windows
3. Downloaded Clifp
4. Put it in the flashpoint folder
5. Moved the folder to the steam deck
6. Added Clifp to steam and enabled compatibility tools so it would run in proton
7. Used the launch command play -t "doeo"

**Expected behavior**
Clifp opens the game doeo

**Screenshots**
![20230917_113500](https://github.com/oblivioncth/CLIFp/assets/24508166/38e98697-2112-4dc2-bdeb-6050df3c5f37)

**Version**
 - CLIFp version 0.95 and 0.96
- Flashpoint version 12

**Additional context**
The linux version works fine for the Linux port of Flashpoint 12.

**Comment by oblivioncth** [comment]
Lol it really feels like 90% of the userbase for this is on Steamdeck, which I feel bad about since I don't have one to test with.

I might be able to configure a VM with Steam OS to get kind of close but I haven't been able to that out yet.

Attach the log of CLIFp from your runs on the steam deck. I can look it over to see if I get any ideas based on where it's stopping, but likely this is ultimately a compatibility issue with WINE :/.

You could also try the dynamic build for the hell of it. Just drop the zip contents in a subfolder within FP12 and run it from there.

**Comment by TheDoomCider** [comment]
[CLIFp.log](https://github.com/oblivioncth/CLIFp/files/12643501/CLIFp.log)

**Comment by TheDoomCider** [comment]
Thanks, I will give that a try.

**Comment by oblivioncth** [comment]
In regards to the log you provided, when it was generated was it one of the "nothing happens" instances or did you get the above error?

How exactly are you starting CLIFp (i.e. what exactly does your call to WINE look like)?

**Comment by TheDoomCider** [comment]
I added Clifp to steam. I did not specify a game still I wanted to make sure the game I was trying to launch was not causing the issue. That log is a mix of nothing happening and getting the error.

**Comment by oblivioncth** [comment]
OK. Can you send me the log from when you try to run a a game?

**Comment by TheDoomCider** [comment]
If I try to run a game, nothing happens and I get no log. However, I was able to get it working in lutris just fine... Not sure why it refuses to work in steam though...?

**Comment by TheDoomCider** [comment]
Definitely, a compatibility issue with proton. It work in lutris with 8.02 but I don't have that as an option in steam.

**Comment by TheDoomCider** [comment]
Never mind, it stopped working in lutris....

**Comment by oblivioncth** [comment]
It's strange that you get nothing when trying to run a game as the log is opened and written to before the command or any arguments are parsed. I wonder if perhaps for some reason proton thinks the arguments are for it and you need to quote them differently?

The termination error might actually be a red hearing as it might just be something with memory not being cleaned up correctly when the program is finishing up and not actually a direct crash. Hmm. Did the shared build change anything?

While not the most hopeful, the only thing I can really do to help try and suss this out is play around with Steam OS in a VM and see if I discover anything, though I don't have time for such a deep dive at the moment.

**Comment by TheDoomCider** [comment]
I couldn't get the shared build to run at all in Steam or Lutris. I understand. I make Steam Deck tutorials and I have someone bugging me to make a Flashpoint 12 tutorial. The linux version is pretty good now but more games work in the Windows version... I'll keep playing around with Steam and Lutris and let you know if I find anything.

**Comment by oblivioncth** [comment]
Gotcha. Yea do let me know if you figure out anything.

It seems there is a somewhat convenient way to debug Windows programs on the deck: https://partner.steamgames.com/doc/steamdeck/debugging

That's likely what I'd need to do to have a chance at figuring out anything. Hopefully it's possible to run a SteamOS in dev mode like it's a real deck, but if not idk maybe I can get a cheap used one or something. Again, not sure yet when I can get to it but I will be trying to help with this issue once I have the time.

**Comment by TheDoomCider** [comment]
Good news, they have updated Flashpoint to address a lot of the sort comings in the native steam deck version. I no longer feel the need to even recommend the windows version of flashpoint 12. Bad news is the update broke compatibility with Clifp...

**Comment by oblivioncth** [comment]
At some point it would be interesting to try the Windows version through Linux Steam in general and see what happens.

Cool that the Linux native package has finally been updated to 12 and works better. I'll try to update things for it here as soon as I can.

**Comment by TheDoomCider** [comment]
Thanks

**Comment by oblivioncth** [comment]
I have my go to test game working foe FP12 on Ubuntu. I still need to refactoring some things, but once I do I'll link you to the dev build so you can try it out for a bit incase something else doesn't work before I mark another release.

**Comment by TheDoomCider** [comment]
Sounds god, thanks for the update :)

**Comment by oblivioncth** [comment]
Ok, while I don't have time to do extensive testing at the moment, the builds of the follow artifact seem to be working with both the standard Linux build (tested on Ubuntu) and the auto/appimage build recommended for Steam Deck (tested on Arch): https://github.com/oblivioncth/CLIFp/actions/runs/6527187018

Let me know if it works for you.

**Comment by TheDoomCider** [comment]
I have only tested the linux version in desktop mode. I am getting a new error now.
![20231016_183551](https://github.com/oblivioncth/CLIFp/assets/24508166/cd95fbeb-6b04-4074-8771-18c6cfa2ed9b)
![20231016_183558](https://github.com/oblivioncth/CLIFp/assets/24508166/9b1ab348-096b-48de-987a-2e7773997d1d)

**Comment by TheDoomCider** [comment]
[clifp.log](https://github.com/oblivioncth/CLIFp/files/12922282/clifp.log)

**Comment by oblivioncth** [comment]
Which build are you using (I'm assuming the steam deck recommended build), and also the obligatory: This same install works with the vanilla launcher?

**Comment by oblivioncth** [comment]
Ok wait just realized that httpd is mainly used with ultimate and indeed even with this special build it was using 'php' as the server not httpd.

Can you send `Data/services.json`?

**Comment by oblivioncth** [comment]
Gave me a scare there for a moment, but awesome, I'm glad it's working well since most people that use the Linux build seem to do so on the deck.

I'll merge this into a new release momentarily so you can just point people to that.

**Comment by TheDoomCider** [comment]
Sorry again about that. However, you were correct. I did have the server set to apache originally.

**Comment by oblivioncth** [comment]
> Sorry again about that. However, you were correct. I did have the server set to apache originally.

No worries. 

I was going to be really shocked though cause since the AppImage build is based on the Windows build it does have http.exe under Legacy, but I was pretty certain that even the vanilla launcher isn't setup to handle launching Windows executables for services (only for games). I checked just to be sure and lo and behold setting the preference to the Appache server causes the vanilla launcher to note a "httpd command not found" in the logs, so I was pretty sure that's what was going on.

**Comment by oblivioncth** [comment]
Fixed with release 0.9.7
