### ISSUE TITLE
[BUG] Certain games don't work.

### ISSUE THREAD

**Issue by polocatfan** [oblivioncth/CLIFp#88]
**Describe the bug**
Certain games fail to download or play when using the Linux version of CLIFp. Haven't tested any other versions.

**To Reproduce**
1. Attempt to run CLIFp to play a game like Bloons 2 or Bullet Bill
2. It errors out

**Expected behavior**
It should have downloaded the game or detected they were downloaded and play the game.

**Screenshots**
![image](https://github.com/user-attachments/assets/32afd97d-e063-48cb-a048-cec9b91fb0c0)

**Version (please complete the following information):**
 - CLIFp version v0.9.11
- Flashpoint version 13 Linux Immutable

**Comment by oblivioncth** [comment]
This actually has already been fixed in dev, but please try the [latest artifacts](https://github.com/oblivioncth/CLIFp/actions/runs/10394213212) from that branch to confirm they work for you.

**Comment by polocatfan** [comment]
oh apologies! didn't see it on the issue page. the artifacts work great!

**Comment by oblivioncth** [comment]
> oh apologies! didn't see it on the issue page. the artifacts work great!

No problem! It's because I ran into it myself, so I wasn't reported. I probably should have made an issue anyway lol.

It sill be in a release soon, just need to test that open PR a little more and get it merged.
